apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    component: server
spec:
  containers:
    - name: server
      image: marscheung/multi-server
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
      env:
        - name: REDIS_HOST
          value: redis-cluster-ip-service
        - name: REDIS_PORT
          value: "6379"
        - name: PGUSER
          value: postgres
        - name: PGHOST
          value: postgres-cluster-ip-service
        - name: PGDATABASE
          value: postgres
        - name: PGPASSWORD
          value: postgres_password
        - name: PGPORT
          value: "5432"
